### PR TITLE
Fix RTD memory issue by using mamba

### PR DESCRIPTION
**Pull request by anissa111**
Summary of changes:
- specify mamba for RTD builds using the instructions [here](https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba)

### CODE REVIEW

**Comment by erogluorhan** [comment]
The latest RTD build for this branch failed. Once it is fixed, I can approve this.

**Review by erogluorhan — COMMENTED** [review]
The latest RTD build for this branch failed. Once it is fixed, I can approve this.

**Comment by anissa111** [comment]
@erogluorhan I thought I'd broken something again, but I re-ran the docs and they're passing now.

**Review by erogluorhan — APPROVED** [review]
Thanks for this fix!

**Pull request merged**
