### PR TITLE
Vector_3

### LINKED ISSUE #16: vector_3
Description: basic vectors

Script URL: https://www.ncl.ucar.edu/Applications/Scripts/vector_3.ncl

Plot URL: https://www.ncl.ucar.edu/Applications/Images/vector_3_lg.png

### PR DESCRIPTION
**Pull request by mnlevy1981**
@maboualidev and I converted [vector_3.ncl](https://www.ncl.ucar.edu/Applications/Scripts/vector_3.ncl) to the python template. We use `quiver()` for the vector plot and rely on @dcherian's `nclize_axis()` and `add_lat_lon_ticklabels()` functions.

Fixes #16 

Based on the same branch used in #29 -- after that PR is accepted, this should show just a single commit / new file.

### CODE REVIEW

**Comment by clyne** [comment]
@mnlevy1981 Is this still a work in progress? It was approved by the reviewer. Thanks!

**Comment by mnlevy1981** [comment]
Let me take one last look at where things stand -- I think this one will be okay to merge (after I add a note about the kludgy "only display every third vector in each direction while we figure out `vcMinDistanceF`")

**Comment by clyne** [comment]
Sounds good. Getting some input from the user community would be helpful for figuring out a best path forward.

**Comment by mnlevy1981** [comment]
Okay, I think this is ready for re-review and then merging. Note that it also uses `geocat.viz` as `gcv`, so it will need to be updated when #50 is addressed.

**Comment by clyne** [comment]
@bonnland please re-review when you have time. Thanks!

**Comment by bonnland** [comment]
@mnlevy1981   Only a couple of minor issues that I see, and I'm not sure how worth mentioning they are.   

First, the vectors along the bottom don't point in the same direction as the NCL version, which may be due to the vcMinDistanceF() function not being used, but still the vectors are large enough in the NCL version to maybe warrant another look, or a slightly more detailed explanation as to why the difference.     

Also, I wonder if the eventual equivalent function to vcMinDistanceF() will end up in geocat.comp, instead of geocat.viz, if it is some kind of number crunching function.    But perhaps not; I don't know if it even matters that much right now. 

Lastly, I tried manually resizing the figure, when running "python vector3.py",  and everything changed properly except the quiver key.   I'm not sure if this is a bug in quiverkey(), or if it is the wrong axis transform being used to describe its location.  

Anyway, that's all I have, and I think it looks awesome outside of these little things.

**Comment by mnlevy1981** [comment]
#bonnland -- thanks for the comments!

> the vectors along the bottom don't point in the same direction as the NCL version, which may be due to the vcMinDistanceF() function not being used

I'll change the subset of `lat` that I use to get the bottom row of vectors to look more like the NCL field

> I wonder if the eventual equivalent function to vcMinDistanceF() will end up in geocat.comp, instead of geocat.viz, if it is some kind of number crunching function

That could be - I was picturing it as a wrapper to `plt.quiver`, which seems like it would go in `gcv`, but I could also see implementing it in a way where `geocat.comp` makes more sense

> Lastly, I tried manually resizing the figure, when running "python vector3.py", and everything changed properly except the quiver key.

Oh, I see what you mean -- it looks like `quiverkey()` is tied to the figure frame (`[0, 1] x [0, 1]`) instead of the axes being plotted. I'll see if I can find a work-around for that... I did notice that changing `figsize` in `plt.subplots()` required coming up with new coordinates for the key which is not ideal

**Comment by mnlevy1981** [comment]
@bonnland This is ready for review again -- I was able to set `coordinates='data'` for `quiverkey()` so the location is tied to the grid (which is much smarter than how I was doing it before), and I modified the `lat` bands we plot to include a slightly lower band that looks closer to the NCL bottom band.

**Comment by mnlevy1981** [comment]
Note that this PR will also include a change to `vector_1`, which suffered from the same resizing issue for the `quiverkey()`.

**Pull request merged**
