### PR TITLE
Removes dataonmap_10 example from master branch

### LINKED ISSUE #273: Remove dataonmap_10 from master
Need to remove dataonmap_10 file that was included in panel_10 merge (PR #261) that is causing doc failures. 

Relevant docs error:
`Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/geocat-examples/checkouts/latest/Plots/WRF/NCL_dataonmap_10.py failed leaving traceback:
Traceback (most recent call last):`

### PR DESCRIPTION
**Pull request by anissa111**
Fixes #273 

Removes dataonmap_10 and WRF/readme.rst from inclusion in panel_10 PR that broke the documentation generation

### CODE REVIEW

**Review by michaelavs — APPROVED** [review]
Thank you for finding and fixing this!

**Comment by anissa111** [comment]
> Thank you for finding and fixing this!

Haha, apparently I didn't! It fixed it on my local, I'll keep poking.

**Comment by anissa111** [comment]
Strange, it looks like it's working when I pull up the branch, but doesn't on the PR

image

Also, it's still failing on dataonmap_10, even though it's been removed.

**Comment by michaelavs** [comment]
> Strange, it looks like it's working when I pull up the branch, but doesn't on the PR
> 
> image
> 
> Also, it's still failing on dataonmap_10, even though it's been removed.

Do you think reversing the merge would fix it? If it's worth anything, I think this is the same build error I would get before I downgraded my matplotlib version when testing dataonmap_10 so maybe something to do with that?

**Comment by anissa111** [comment]
> Do you think reversing the merge would fix it? If it's worth anything, I think this is the same build error I would get before I downgraded my matplotlib version when testing dataonmap_10 so maybe something to do with that?

I think reversing the merge would, but this method should also work. When you click on the failing commit and actually open the building docs tab, it shows as working? I'm pretty sure this PR will fix it, but I have no idea why the docs are trying to build an example that I removed.

**Review by erogluorhan — APPROVED** [review]

**Comment by anissa111** [comment]
Note: the docs are generating fine on the PR, but the checks are showing as failed because the docs are failing on the pull_request_target, which, of course, is master and is what the PR is trying to fix. We have run a readthedocs generation on this branch separately, which generates fine, and is why we're approving and merging a "failing" PR.

**Comment by michaelavs** [comment]
Just for my own knowledge because the skewt_3 PR is having the same dilemma when building, when this PR merges, that ~should~ fix the build problem, correct? Currently can't build the branch locally or on github. When I check why, it is showing that dataonmap is the culprit (but dataonmap can build just fine in both places ).

**Comment by anissa111** [comment]
> Just for my own knowledge because the skewt_3 PR is having the same dilemma when building, when this PR merges, that should fix the build problem, correct? Currently can't build the branch locally or on github. When I check why, it is showing that dataonmap is the culprit (but dataonmap can build just fine in both places ).

Yeah! I'm assuming that you branched off the current master branch for the skewt_3, which just carried its issues over into your branch. When we get this one merged, merging the fixed master back into your branch should fix the issues.

**Pull request merged**
