### PR TITLE
Vector_4

### LINKED ISSUE #15: vector_4
Description: basic vectors

Script URL: https://www.ncl.ucar.edu/Applications/Scripts/vector_4.ncl

Plot URL: https://www.ncl.ucar.edu/Applications/Images/vector_4_lg.png

### PR DESCRIPTION
**Pull request by mnlevy1981**
@maboualidev and I converted `vector_4.ncl` to the python template. We use `quiver()` for the vector plot and rely on @dcherian's `nclize_axis()`, `add_lat_lon_ticklabels()`, and `truncate_colormap()` functions.

Fixes #15

Based on the same branch used in #34 -- after that PR is accepted, this should show just a few commits and a single new file. Note it requires the environment in #37 (specifically the `cmaps` package).

### CODE REVIEW

**Comment by mnlevy1981** [comment]
The glaring defect in this PR is that python doesn't offer good alternatives to `CurlyVector` or `vcMinDistanceF`. The former is a bummer, but we can deal with straight vectors. The latter is potentially a deal-breaker, as getting the density of the arrows right is important.

**Comment by clyne** [comment]
@mnlevy1981 is this still a WIP? Thanks!

**Comment by mnlevy1981** [comment]
I think this one needs both `vcMinDistanceF` and some version of `CurlyVector` to look good... so I can add a few caveats to the notebook and then let it be merged, or it can stay a WIP until `geocat-viz` is updated.

**Comment by clyne** [comment]
I think adding some comments describing the difficulties with reproducing the NCL plots and going ahead and merging it are a good plan. As with #34 , this provides an opportunity to gather feedback to help assess priorities (and maybe other ideas on how to resolve). Thanks!

**Comment by mnlevy1981** [comment]
This is ready for review, and will also need to be updated when #50 is resolved.

**Comment by clyne** [comment]
Aside from the inability to create curly vectors with matplotlib this looks great. Just one difference from the NLC plot that hopefully can easily be corrected: the subtitles ("temperature" and "K") present in the NCL plot are missing from the Python version

**Comment by mnlevy1981** [comment]
@clyne 

> the subtitles ("temperature" and "K") present in the NCL plot are missing from the Python version

weird, they are showing up for me:

sphx_glr_vector_4_001

The plot above is just the result of me running `make html` from bf5fa2c. That said, I can play with the figure size a little more in the morning. I know I was having a little trouble figuring out the best `y`-dimension in the `figsize` argument to `plt.subplots()` when I was working on this, and maybe I cut it too close for some environments?

**Comment by clyne** [comment]
Oh, now I see them. I guess the issue is that in the NCL plots this annotation is at the top of the plot, and in the Python version it's along the bottom:

https://www.ncl.ucar.edu/Applications/Images/vector_4_lg.png

**Comment by mnlevy1981** [comment]
Yeah, I should have mentioned that in the PR -- I think I was so caught up in trying to get the vector spacing and coloring correct, that by the time it finished I had forgotten that I moved the label. I moved it because it seems like the color bar is a better place for that label, but I can put it back in the title if you'd prefer.

**Comment by clyne** [comment]
Our goal initially is to make the plots resemble NCL plots as closely as possible just to demonstrate to NCL users that it can be done, and also show them how to do it. It’s a tough sell in some cases, so at least for now we’re making an effort to produce clones. I’m sure we will relax that at some point. So if you wouldn’t mind moving the subtitles that would be terrific. Thanks, Mike!

> On Jan 28, 2020, at 8:52 AM, Michael Levy <notifications@github.com> wrote:
> 
> Yeah, I should have mentioned that in the PR -- I think I was so caught up in trying to get the vector spacing and coloring correct, that by the time it finished I had forgotten that I moved the label. I moved it because it seems like the color bar is a better place for that label, but I can put it back in the title if you'd prefer.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by mnlevy1981** [comment]
> Our goal initially is to make the plots resemble NCL plots as closely as possible just to demonstrate to NCL users that it can be done, and also show them how to do it.

Sounds good - I've updated both this PR and the `vector_3` plot to look more like the NCL original.

**Pull request merged**
