### PR TITLE
Examples plotting unstructured grids

### PR DESCRIPTION
**Pull request by clyne**
This PR provides two quick-and-dirty examples demonstrating one option for plotting unstructured grid data from CAM-SE and MPAS-A GCMs. Much work remains to turn these into user-ready examples

### CODE REVIEW

**Comment by erogluorhan** [comment]
Thanks for putting these significant unstructured plots all together.

@anissa111 and @michaelavs I've added you both as well as myself as reviewers to this PR since there is plenty of novelty and research opportunity through these unstructured gridding effort. Please have a thorough review of it, cand we can further discuss through reviews here or else where.

**Comment by clyne** [comment]
@erogluorhan I don't think this draft PR is ready for review per se. It's more of a discussion point. I suggest that after we meet with James Bednar today we discuss how to move forward.

**Comment by erogluorhan** [comment]
> @erogluorhan I don't think this draft PR is ready for review per se. It's more of a discussion point. I suggest that after we meet with James Bednar today we discuss how to move forward.

Sounds good, thanks for the clarification! I think I wasn't clear enough by using the term "review". I meant to say there is a novel implementation here, where @michaelavs and @anissa111 would have a look at as well and be a part of ongoing discussions. In regards to "review", yes, we don't necessarily review this PR for merging purposes as in the regular PRs. 

Sorry for any confusions :)

**Comment by clyne** [comment]
No worries!

**Comment by erogluorhan** [comment]
@clyne when it comes to actually running the code, I cannot locate the data files you used in each script anywhere like GLADE or ncl test data sets. Could you tell whether they are located anywhere accessible or put them into GLADE?

**Comment by clyne** [comment]
> @clyne when it comes to actually running the code, I cannot locate the data files you used in each script anywhere like GLADE or ncl test data sets. Could you tell whether they are located anywhere accessible or put them into GLADE?

The CAM-SE data are in /glade/p/cisl/vast/vapor/data/Source/CAM/NotSupported/CAM-SE, and the MPAS-A data are in /glade/p/cisl/vast/vapor/data/Source/MPAS/MPAS_V4.0. I left a note in the comments, but it's easy to miss.

**Comment by erogluorhan** [comment]
Thanks!

**Comment by erogluorhan** [comment]
> I left a note in the comments, but it's easy to miss.

Ah yes, noticed that now. Thanks again!

**Pull request closed without merging**
