### PR TITLE
Taylor 8

### PR DESCRIPTION
**Pull request by doqhne**
Resolves issue #465 

Original NCL plot:
https://www.ncl.ucar.edu/Applications/Images/taylor_8_lg.png

Python plot:
taylor_8_python

### CODE REVIEW

**Review by michaelavs — APPROVED** [review]
Looks good to me!

**Comment by anissa111** [comment]
Note will need to merge #457 first

**Review by anissa111 — APPROVED** [review]

**Comment by hCraker** [comment]
@doqhne I noticed on my local that the numbered labels slightly overlap with the scatter plot markers, but they don't overlap in the image you included when you opened this PR. Is this just on my end or is anyone else seeing this? @michaelavs @anissa111 
image

**Comment by hCraker** [comment]
> @doqhne I noticed on my local that the numbered labels slightly overlap with the scatter plot markers, but they don't overlap in the image you included when you opened this PR. Is this just on my end or is anyone else seeing this? @michaelavs @anissa111

Any word on this? I just updated my conda environment, but the labels still overlap. I don't know if it's a bug from another package or if my local version/environment has something wrong with it. @doqhne @anissa111 @michaelavs

**Comment by anissa111** [comment]
> Any word on this? I just updated my conda environment, but the labels still overlap. I don't know if it's a bug from another package or if my local version/environment has something wrong with it. @doqhne @anissa111 @michaelavs

Looking into it now!

**Comment by anissa111** [comment]
@hCraker I am getting three different results. 

When I run the example in my IDE, I get the non-overlapping picture as expected. When I generate the docs locally, I get the overlap that you posted. When I run the example from the terminal, I get an even worse overlap.

The `TaylorDiagram` arg that controls this is directly passed to `matplotlib.axes.Axes.annotate` and I bet the way it's calculated is differing slightly depending on where we're plotting it. 

I'm going to go based on what looks best on RTD? My local docs generation seems to most closely match the RTD. I'm going to push a change based on that and see if RTD looks better.

**Comment by hCraker** [comment]
@anissa111 That definitely looks better on RTD! image

**Review by hCraker — APPROVED** [review]
Great work! 🎉

**Pull request merged**
