### PR TITLE
Adding new polyg_19 for build testing

### PR DESCRIPTION
**Pull request by michaelavs**

### CODE REVIEW

**Comment by michaelavs** [comment]
@pilotchute @erogluorhan @anissa111 I found separating the main plot function into two (nearly) identical functions allows to the code to run in about 3.5 minutes compared to previous 6-10 minute runs. It seems this is a consistent outcome so I would like to test if this 1. continues happening after merge and 2. If this is fast enough to be built successfully. I added you all as reviewers so everyone is on the same page, and if anything seems wrong with the code overall (formatting, functionality, etc), I am open to input!

**Comment by erogluorhan** [comment]
> @pilotchute @erogluorhan @anissa111 I found separating the main plot function into two (nearly) identical functions allows to the code to run in about 3.5 minutes compared to previous 6-10 minute runs. It seems this is a consistent outcome so I would like to test if this 1. continues happening after merge and 2. If this is fast enough to be built successfully. I added you all as reviewers so everyone is on the same page, and if anything seems wrong with the code overall (formatting, functionality, etc), I am open to input!

Thanks for the information! It seems to be failing in the same way @anissa111 mentioned today about her commits. I did not have a chance to dig into the failures yet, but you may want to have a look at the latest commits and so to see what's going on with Sphinx builds of the repo.

**Comment by michaelavs** [comment]
@anissa111 @pilotchute Could one of you double check the build error reason on this PR? I'm pretty sure it is showing that the error is not coming from this specific code but instead when trying to build panel_1. I am able to get Sphinx to build locally, so I'm not sure if there is truly a bug in another code, or if it is still stemming from polyg_19 taking too long to process

**Comment by anissa111** [comment]
> @anissa111 @pilotchute Could one of you double check the build error reason on this PR? I'm pretty sure it is showing that the error is not coming from this specific code but instead when trying to build panel_1. I am able to get Sphinx to build locally, so I'm not sure if there is truly a bug in another code, or if it is still stemming from polyg_19 taking too long to process

I was looking at that. I just tried to pull in the changes from master directly, maybe that will help. If the checks fail again I'll pull it down into local and play around!

**Comment by michaelavs** [comment]
@anissa111 It looks like that was the issue, I definitely should've noticed that as I had to do that to the native_2 branch this morning as well! It looks like the checks have passed for building the documentation pages, so hopefully that's a good sign for if we merge this version!

**Comment by anissa111** [comment]
> @anissa111 It looks like that was the issue, I definitely should've noticed that as I had to do that to the native_2 branch this morning as well! It looks like the checks have passed for building the documentation pages, so hopefully that's a good sign for if we merge this version!

@erogluorhan  I've noticed this on a couple of things in this repo, but does anybody have any idea why the docs seem to be passing, but the status isn't being reported back to the checks tab in PRs?

**Comment by michaelavs** [comment]
> > @anissa111 It looks like that was the issue, I definitely should've noticed that as I had to do that to the native_2 branch this morning as well! It looks like the checks have passed for building the documentation pages, so hopefully that's a good sign for if we merge this version!
> 
> @erogluorhan I've noticed this on a couple of things in this repo, but does anybody have any idea why the docs seem to be passing, but the status isn't being reported back to the checks tab in PRs?

I noticed in a couple of mine, that the yapf formatter is the check that isn't finalizing (either passing or failing). Could this be where the issue is?

**Review by erogluorhan — APPROVED** [review]
LGTM, thanks all for the solution!

**Review by pilotchute — APPROVED** [review]

**Pull request merged**
