### PR TITLE
polyg_8

### LINKED ISSUE #168: polyg_8
Description: Divide data into different bins and use different colored markers for each bin, create a custom legend

Script URL: https://www.ncl.ucar.edu/Applications/Scripts/polyg_8.ncl
Plot URL: https://www.ncl.ucar.edu/Applications/Images/polyg_8_lg.png

Category: Polygon

### PR DESCRIPTION
**Pull request by hCraker**
Closes #168 
image

### CODE REVIEW

**Comment by hCraker** [comment]
image

**Comment by michaelavs** [comment]
Looks great so far! If you want to bold the plot title, you can use 'fontweight' if you change to using the plt.title() function instead of the geocat convenience function. But, if not, I think this code is good to go!

**Comment by hCraker** [comment]
> Looks great so far! If you want to bold the plot title, you can use 'fontweight' if you change to using the plt.title() function instead of the geocat convenience function. But, if not, I think this code is good to go!

That's a great suggestion. Unfortunately, I just realized that you can't change the `fontweight` using the geocat-viz utility function `set_titles_and_labels`. This is definitely a feature we should add in the future. For now, I think I'm going to leave the title as is so this example shows how to use the utility function.

**Comment by hCraker** [comment]
> @hCraker when I try to generate the notebook for this I get:
> 
> Unexpected failing examples:
> /glade/p/VAST/VAPOR/tmp/git-sandbox/rose/Plots/Trajectories/NCL_polyg_14.py failed leaving traceback:
> Traceback (most recent call last):
> File "/Users/clyne/tmp/miniconda/envs/geocat-examples/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 159, in call_memory
> return 0., func()
> File "/Users/clyne/tmp/miniconda/envs/geocat-examples/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 466, in **call**
> exec(self.code, self.fake_main.**dict**)
> File "/glade/p/VAST/VAPOR/tmp/git-sandbox/rose/Plots/Trajectories/NCL_polyg_14.py", line 23, in
> from geographiclib.geodesic import Geodesic
> ModuleNotFoundError: No module named 'geographiclib'

I'm not sure why that happened. I had the same error, but after my latest push it's no longer occurring. I don't know what was wrong since all I changed just now was some formatting and comments.

**Comment by clyne** [comment]
> > @hCraker when I try to generate the notebook for this I get:
> > Unexpected failing examples:
> > /glade/p/VAST/VAPOR/tmp/git-sandbox/rose/Plots/Trajectories/NCL_polyg_14.py failed leaving traceback:
> > Traceback (most recent call last):
> > File "/Users/clyne/tmp/miniconda/envs/geocat-examples/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 159, in call_memory
> > return 0., func()
> > File "/Users/clyne/tmp/miniconda/envs/geocat-examples/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 466, in **call**
> > exec(self.code, self.fake_main.**dict**)
> > File "/glade/p/VAST/VAPOR/tmp/git-sandbox/rose/Plots/Trajectories/NCL_polyg_14.py", line 23, in
> > from geographiclib.geodesic import Geodesic
> > ModuleNotFoundError: No module named 'geographiclib'
> 
> I'm not sure why that happened. I had the same error, but after my latest push it's no longer occurring. I don't know what was wrong since all I changed just now was some formatting and comments.

I think this is something we need to figure out on our end. Thoughts on this  @pilotchute, @erogluorhan ? FYI I've tried rebuilding my conda environment from scratch.

**Comment by erogluorhan** [comment]
> I think this is something we need to figure out on our end. Thoughts on this @pilotchute, @erogluorhan ? FYI I've tried rebuilding my conda environment from scratch.

@hCraker One of the recent PRs added dependency for `geographiclib` package, which you can see under `GeoCAT-examples/conda_environment.yml`. All you need to do is `conda update` your `geocat-examples` environment. @clyne didn't it work for you to build your environment from scratch? If so, can you clarify if you can see `geographiclic` dependency within your **.yml** file?

**Comment by hCraker** [comment]
> > I think this is something we need to figure out on our end. Thoughts on this @pilotchute, @erogluorhan ? FYI I've tried rebuilding my conda environment from scratch.
> 
> @hCraker One of the recent PRs added dependency for `geographiclib` package, which you can see under `GeoCAT-examples/conda_environment.yml`. All you need to do is `conda update` your `geocat-examples` environment. @clyne didn't it work for you to build your environment from scratch? If so, can you clarify if you can see `geographiclic` dependency within your **.yml** file?

I've updated my environment. I'm no longer receiving errors regarding `geographiclib`

**Comment by erogluorhan** [comment]
> I've updated my environment. I'm no longer receiving errors regarding `geographiclib`

Sounds good.

**Comment by clyne** [comment]
> > I think this is something we need to figure out on our end. Thoughts on this @pilotchute, @erogluorhan ? FYI I've tried rebuilding my conda environment from scratch.
> 
> @hCraker One of the recent PRs added dependency for `geographiclib` package, which you can see under `GeoCAT-examples/conda_environment.yml`. All you need to do is `conda update` your `geocat-examples` environment. @clyne didn't it work for you to build your environment from scratch? If so, can you clarify if you can see `geographiclic` dependency within your **.yml** file?

I have geographiclib in my conda_environment.yml file, but I get an error when I try to update it:

(geocat-examples) bash-3.2$ !581
conda update --file conda_environment.yml 

CondaValueError: could not parse 'name: geocat-examples' in: conda_environment.yml

**Pull request merged**
