### PR TITLE
conOncon1 with add_right_hand_axis

### PR DESCRIPTION
**Pull request by Jiaqi-beep**
Current plot:
image

Plot with add_right_hand_axis:
image

### CODE REVIEW

**Comment by erogluorhan** [comment]
@michaelavs @anissa111 is the next step to add this utility function into geocat-viz and to use from there instead?

**Comment by erogluorhan** [comment]
@anissa111 @michaelavs What is our plan with this?

**Comment by pilotchute** [comment]
duplicate of #464 ?

**Comment by jukent** [comment]
So this function is already in geocat-viz, going to remove the function block from the example and call in geocat-viz

**Review by jukent — CHANGES_REQUESTED** [review]
I will fix this PR to use the new pressure height function before merging. The right y-axis is wrong.

**Comment by jukent** [comment]
image

New plot using new height from pressure axis function

**Comment by jukent** [comment]
Will fail until next GeoCAT-Viz release

**Review by jukent — APPROVED** [review]

**Comment by kafitzgerald** [comment]
Do we know why the right axis is still slightly different from the original NCL plot?  I just noticed when looking through the history here.  

Looks like it might be a difference in the calculation coming from metpy, but I don't know why there'd be a diff.  

https://www.ncl.ucar.edu/Applications/Images/conOncon_1_lg.png

**Comment by jukent** [comment]
Yes it is because there is a difference in the "standard atmosphere" used for conversion from pressure to height in metpy's function and I'm NCL. It doesn't seem worth supporting our own pressure height conversion at this time.

**Comment by jukent** [comment]
If we do chose to change the height-pressure conversion, that would be in viz but we'd use the same function call here.

**Pull request merged**
