### PR TITLE
Remove "Edit on Github" buttons from RTD builds

### PR DESCRIPTION
**Pull request by anissa111**
Addresses #298 

Summary of changes:
- overrides sphinx theme read the docs button

I have made the [sphinx_delete branch visible on RTD](https://geocat-examples.readthedocs.io/en/sphinx_delete/) so you can go look at how the change affects the documentation generation.

### CODE REVIEW

**Review by erogluorhan — CHANGES_REQUESTED** [review]
Removal of the buttons looks good to me. Just for helpg the readers head to the Github repo, please add such a "Support" page and repo links into the RTD like the one in geocat-comp's s follows:

image

**Comment by anissa111** [comment]
I have updated the docs to include a support page that links to the repo. It's building on RTD now!

**Review by michaelavs — APPROVED** [review]
Looks good to me! Thanks for updating!

**Review by erogluorhan — APPROVED** [review]
LGTM

**Pull request merged**
