### PR TITLE
Vector 5

### PR DESCRIPTION
**Pull request by Jiaqi-beep**
- NCL Script: https://www.ncl.ucar.edu/Applications/Scripts/vector_5.ncl
- NCL Plot: https://www.ncl.ucar.edu/Applications/Images/vector_5_lg.png
- Issue: #376 
hello

### CODE REVIEW

**Comment by Jiaqi-beep** [comment]
Just found a bug that the arrow directions are the opposite of original plot. Working on it.

**Comment by erogluorhan** [comment]
> Just found a bug that the arrow directions are the opposite of original plot. Working on it.
> 
> Edit: Not sure if this is fixable.

Any update on this?

**Comment by anissa111** [comment]
> Any update on this?

@erogluorhan, this is an issue that stems from the lack of a good way to recreate curly vectors plots in python

**Comment by erogluorhan** [comment]
> > Any update on this?
> 
> @erogluorhan, this is an issue that stems from the lack of a good way to recreate curly vectors plots in python

Okay, so, no actual error with the vector directions generated here, right?

Then, investigating curly vectors sounds like an opportunity here. Any ideas?

**Comment by Jiaqi-beep** [comment]
> > > Any update on this?
> > 
> > 
> > @erogluorhan, this is an issue that stems from the lack of a good way to recreate curly vectors plots in python
> 
> Okay, so, no actual error with the vector directions generated here (w.r.t. data), right?
> 
> Then, investigating curly vectors sounds like an opportunity here. Any ideas?

@erogluorhan Yep. There might be a way to do so with streamplot like in [this example](https://stackoverflow.com/questions/51843313/flow-visualisation-in-python-using-curved-path-following-vectors), but I didn't try much.

**Comment by michaelavs** [comment]
So I have a lot of questions about this and why it may be the solution, but here is a short version and we can discuss further tomorrow:
I opened an issue with matplotlib about the potential issue with streamplots and how it could be scaling/interpolating the data incorrectly. Basically, they said "Looks like your scale (wscale) is in the wrong direction, try editing that and see if the issue persists." Well, I went ahead and multiplied ```wscale``` on line 80 by -1 to see what happened. The plot is fixed. Or at least, in better condition than it was. 
image

Again, no idea why we needed to multiply by -1 because it isn't in the NCL code, but I guess that was the fix? @Jiaqi-beep, I think you had mentioned maybe implementing this as a fix previously, but hadn't because nothing in the NCL code implied you should, so I guess unless theres a big reason I'm missing to not use this fix, I say go for it.

**Comment by Jiaqi-beep** [comment]
@michaelavs Thanks so much for helping out with this! I'll update it.

**Comment by anissa111** [comment]
This looks good, but I'm getting some funny warnings

```
/Users/anissaz/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/metpy/interpolate/one_dimension.py:137: UserWarning: Interpolation point out of data bounds encountered
  warnings.warn('Interpolation point out of data bounds encountered')
/Users/anissaz/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/metpy/interpolate/one_dimension.py:137: UserWarning: Interpolation point out of data bounds encountered
  warnings.warn('Interpolation point out of data bounds encountered')
```

Are any of you getting this on your local?

**Comment by Jiaqi-beep** [comment]
> This looks good, but I'm getting some funny warnings
> 
> ```
> /Users/anissaz/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/metpy/interpolate/one_dimension.py:137: UserWarning: Interpolation point out of data bounds encountered
>   warnings.warn('Interpolation point out of data bounds encountered')
> /Users/anissaz/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/metpy/interpolate/one_dimension.py:137: UserWarning: Interpolation point out of data bounds encountered
>   warnings.warn('Interpolation point out of data bounds encountered')
> ```
> 
> Are any of you getting this on your local?

I am. I think it's from scipy's interp2d on line 124 and 125

**Review by michaelavs — APPROVED** [review]
Looks good to me!

**Review by anissa111 — APPROVED** [review]
Looks great!

**Pull request merged**
