### PR TITLE
Added citing info

### PR DESCRIPTION
**Pull request by erogluorhan**
Adds "how to cite" info into README.md and RTD docs.

Also adds `dependabot` as it has been working smoothly with geocat-comp.

### CODE REVIEW

**Review by michaelavs — APPROVED** [review]
Looks good to me, thanks for adding this!

**Review by anissa111 — COMMENTED** [review]
This is not the point of this PR, but are we not allowing for different DOIs to cite different versions of our packages? The DOI I see listed in this PR links to the geocat homepage instead of any sort of repository. Is there going to be a way to cite the project as a whole vs different releases?

**Comment by erogluorhan** [comment]
> This is not the point of this PR, but are we not allowing for different DOIs to cite different versions of our packages? The DOI I see listed in this PR links to the geocat homepage instead of any sort of repository. Is there going to be a way to cite the project as a whole vs different releases?

Great question! For now, we hope that a single overarching DOI would work for all of our software assets and our reporting purposes. If you check the citation text of GeoCAT-comp, you will see that we are recommending to cite a specific version number in the text. But for GeoCAT-examples, there is no version we keep track of, so we are only recommending to cite that it is "GeoCAT-examples" package.

If in the future, we need separate DOIs for each version of each software tool, we can do that.

**Review by anissa111 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
