### PR TITLE
Panel 41

### PR DESCRIPTION
**Pull request by Jiaqi-beep**
- Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/panel_41.ncl
- Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/panel_41_lg.png
image

### CODE REVIEW

**Review by anissa111 — COMMENTED** [review]
This looks almost perfect! My only comment is that I think the left and right titles should be raised a little bit as to not touch the top tick marks:

image

**Comment by michaelavs** [comment]
This looks good overall!

One thing I noticed was that there were white spots where data is missing on some of the plots. After looking into this, I found that the levels don't encompass all of the data points for this set (even though they match what the NCL version provided). However, if we change the levels to match the data, then the colorbar gets thrown off/doesn't match the NCL version. If anyone knows of a work around for this where the filled contours can have one range of levels and the colorbar has another range of levels, I think that would be the best route for this plot. However, I'm not 100% if there is a clean and easy way to make that happen. So if there isn't, I am totally fine approving this PR with the contour levels as is, but wanted to check on if anyone else maybe knew of a way to fix this that I don't.

**Comment by Jiaqi-beep** [comment]
> This looks good overall!
> 
> One thing I noticed was that there were white spots where data is missing on some of the plots. After looking into this, I found that the levels don't encompass all of the data points for this set (even though they match what the NCL version provided). However, if we change the levels to match the data, then the colorbar gets thrown off/doesn't match the NCL version. If anyone knows of a work around for this where the filled contours can have one range of levels and the colorbar has another range of levels, I think that would be the best route for this plot. However, I'm not 100% if there is a clean and easy way to make that happen. So if there isn't, I am totally fine approving this PR with the contour levels as is, but wanted to check on if anyone else maybe knew of a way to fix this that I don't.

I think creating a mappable allows us to customize color bar, or maybe simply specifying ticks argument for plt.colorbar()? I'll work on this and thank you for spotting the data missing.

**Review by anissa111 — APPROVED** [review]
This looks good!

**Pull request merged**
