### PR TITLE
Remove isort

### PR DESCRIPTION
**Pull request by anissa111**
This PR:
- removes the isort pre-commit hook
- reverts weird formatting caused by alphabetization of imports
- adds a consistent new line before and after the imports themselves
- standardizes the import block comment
- removes some unused imports
- fixes a typo

### CODE REVIEW

**Review by michaelavs — APPROVED** [review]
Thanks for making these changes! I'm glad that the files could be reverted to their previous form before isort so avoid editing by hand!

**Comment by anissa111** [comment]
> Thanks for making these changes! I'm glad that the files could be reverted to their previous form before isort so avoid editing by hand!

Haha, I still had to check all the files by hand :(

**Comment by michaelavs** [comment]
> > Thanks for making these changes! I'm glad that the files could be reverted to their previous form before isort so avoid editing by hand!
> 
> Haha, I still had to check all the files by hand :(

Oh no, and I was so excited too!! Thank you for checking them all by hand though!

**Comment by erogluorhan** [comment]
@anissa111 I'd like to give this a review, but the CI tests seem to have been cancelled and not ran/passed since then. Do I need to know anything here?

**Comment by anissa111** [comment]
> @anissa111 I'd like to give this a review, but the CI tests seem to have been cancelled and not ran/passed since then. Do I need to know anything here?

Github actions are currently down. I am checking the status periodically, but whenever I try to run the tests at the moment, they cancel themselves.

**Comment by anissa111** [comment]
@erogluorhan Github actions are back up and the checks all went through!

**Review by erogluorhan — APPROVED** [review]

**Pull request merged**
